//学完js再优化
function fun1() {
  document.getElementById("Monday").classList.add('active');
  document.getElementById("a-Monday").classList.add('active');
  document.getElementById("Tuesday").classList.remove('active');
  document.getElementById("a-Tuesday").classList.remove('active');
  document.getElementById("Wednesday").classList.remove('active');
  document.getElementById("a-Wednesday").classList.remove('active');
  document.getElementById("Thursday").classList.remove('active');
  document.getElementById("a-Thursday").classList.remove('active');
  document.getElementById("Friday").classList.remove('active');
  document.getElementById("a-Friday").classList.remove('active');
  document.getElementById("Saturday").classList.remove('active');
  document.getElementById("a-Saturday").classList.remove('active');
}
function fun2() {
  document.getElementById("Monday").classList.remove('active');
  document.getElementById("a-Monday").classList.remove('active');
  document.getElementById("Tuesday").classList.add('active');
  document.getElementById("a-Tuesday").classList.add('active');
  document.getElementById("Wednesday").classList.remove('active');
  document.getElementById("a-Wednesday").classList.remove('active');
  document.getElementById("Thursday").classList.remove('active');
  document.getElementById("a-Thursday").classList.remove('active');
  document.getElementById("Friday").classList.remove('active');
  document.getElementById("a-Friday").classList.remove('active');
  document.getElementById("Saturday").classList.remove('active');
  document.getElementById("a-Saturday").classList.remove('active');
}
function fun3() {
  document.getElementById("Monday").classList.remove('active');
  document.getElementById("a-Monday").classList.remove('active');
  document.getElementById("Tuesday").classList.remove('active');
  document.getElementById("a-Tuesday").classList.remove('active');
  document.getElementById("Wednesday").classList.add('active');
  document.getElementById("a-Wednesday").classList.add('active');
  document.getElementById("Thursday").classList.remove('active');
  document.getElementById("a-Thursday").classList.remove('active');
  document.getElementById("Friday").classList.remove('active');
  document.getElementById("a-Friday").classList.remove('active');
  document.getElementById("Saturday").classList.remove('active');
  document.getElementById("a-Saturday").classList.remove('active');
}
function fun4() {
  document.getElementById("Monday").classList.remove('active');
  document.getElementById("a-Monday").classList.remove('active');
  document.getElementById("Tuesday").classList.remove('active');
  document.getElementById("a-Tuesday").classList.remove('active');
  document.getElementById("Wednesday").classList.remove('active');
  document.getElementById("a-Wednesday").classList.remove('active');
  document.getElementById("Thursday").classList.add('active');
  document.getElementById("a-Thursday").classList.add('active');
  document.getElementById("Friday").classList.remove('active');
  document.getElementById("a-Friday").classList.remove('active');
  document.getElementById("Saturday").classList.remove('active');
  document.getElementById("a-Saturday").classList.remove('active');
}
function fun5() {
  document.getElementById("Monday").classList.remove('active');
  document.getElementById("a-Monday").classList.remove('active');
  document.getElementById("Tuesday").classList.remove('active');
  document.getElementById("a-Tuesday").classList.remove('active');
  document.getElementById("Wednesday").classList.remove('active');
  document.getElementById("a-Wednesday").classList.remove('active');
  document.getElementById("Thursday").classList.remove('active');
  document.getElementById("a-Thursday").classList.remove('active');
  document.getElementById("Friday").classList.add('active');
  document.getElementById("a-Friday").classList.add('active');
  document.getElementById("Saturday").classList.remove('active');
  document.getElementById("a-Saturday").classList.remove('active');
}
function fun6() {
  document.getElementById("Monday").classList.remove('active');
  document.getElementById("a-Monday").classList.remove('active');
  document.getElementById("Tuesday").classList.remove('active');
  document.getElementById("a-Tuesday").classList.remove('active');
  document.getElementById("Wednesday").classList.remove('active');
  document.getElementById("a-Wednesday").classList.remove('active');
  document.getElementById("Thursday").classList.remove('active');
  document.getElementById("a-Thursday").classList.remove('active');
  document.getElementById("Friday").classList.remove('active');
  document.getElementById("a-Friday").classList.remove('active');
  document.getElementById("Saturday").classList.add('active');
  document.getElementById("a-Saturday").classList.add('active');
}
